$schema: https://azuremlschemas.azureedge.net/latest/schedule.schema.json

name: tom-coord-nightly-schedule
display_name: ToM Coordination Nightly Schedule

trigger:
  type: recurrence
  frequency: day
  interval: 1
  time_zone: UTC
  schedule:
    hours: [2]
    minutes: [0]

create_job:
  job: ./pipeline.yml
